# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: alfredo.diaz@therore.net
email: alfredo.diaz@therore.net
description: A bit of open source, java ecosystem and programming tips
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://therore.net/" # the base hostname & protocol for your site
github_username:  alfredodiaz

# Build settings
markdown: kramdown

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: alfredo.diaz@therore.net
  avatar: # avatar.png
  gravatar: # 
  description: A bit of open source, java ecosystem and programming tips

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   therore.net blog is created by <a href="/about/">Alfredo Diaz</a>
   </br>
   <span style="font-size:85%">Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a></span>

  # Icons
  rss: true
  email_address: alfredo.diaz@therore.net
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "alfredodiaz"
  google_plus: "104718757519673756328"
  #instagram: 
  linkedin: "http://www.linkedin.com/in/alfredodiaztherore" # Full URL
  pinterest:
  reddit:
  slideshare: 
  soundcloud:
  stack_exchange: http://stackexchange.com/users/3617951/alfredo-diaz?tab=accounts
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube: "UCOQ1"

  # Scripts
  google_analytics: UA-71841148-1
  disqus_shortname: alfredodiaztherore
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"
gems: ["jekyll-paginate"]

# BUILD SETTINGS
markdown: kramdown
#markdown: redcarpet
#highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
#  syntax_highlighter_opts:
#    line_numbers: true
    
sass:
  sass_dir: _sass
  style: :compressed
